In [61]:
a = [[1,2,3], [0,1,0]]
a

[[1, 2, 3], [0, 1, 0]]

In [46]:
import numpy as np

In [64]:
a = np.array(a)

In [63]:
type(a)

list

In [65]:
type(a)

numpy.ndarray

In [66]:
a.shape

(2, 3)

In [67]:
a.ndim

2

In [68]:
a.size

6

In [69]:
a.dtype

dtype('int64')

In [70]:
a.itemsize

8

In [71]:
a.data

In [100]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [102]:
b = np.array([[1,2], [3,4]], dtype=complex)
b

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [103]:
c = np.zeros( (2,3) )
c

array([[0., 0., 0.],
       [0., 0., 0.]])

In [104]:
d = np.ones( (3,4) )
d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [107]:
e = np.empty( (4,5) )
e

array([[ 6.94365884e-310,  4.64142632e-310,  6.94364792e-310,
         1.30050805e+282,  6.94364791e-310],
       [ 4.64142632e-310, -3.04997995e-090,  6.94364791e-310,
         4.64142632e-310,  8.35511796e+140],
       [ 6.94364791e-310,  4.64142632e-310, -4.11317263e+033,
         6.94364791e-310,  6.94364792e-310],
       [-6.74661268e+205,  6.94364791e-310,  6.94364792e-310,
        -1.80839214e-065,  6.94364791e-310]])

In [109]:
f = np.ones( (2,2,3) )
f

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [112]:
np.arange(5, 15, 2)

array([ 5,  7,  9, 11, 13])

In [113]:
np.arange(0,2,0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [114]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [136]:
a = np.array([20,30,40,50])
b = np.arange(4)
a,b

(array([20, 30, 40, 50]), array([0, 1, 2, 3]))

In [137]:
a-b

array([20, 29, 38, 47])

In [139]:
b**2

array([0, 1, 4, 9])

In [140]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [141]:
a<35

array([ True,  True, False, False])

In [142]:
A = np.array([[1,1], [0,1]])
B = np.array([[2,0], [3,4]])
A,B

(array([[1, 1],
        [0, 1]]), array([[2, 0],
        [3, 4]]))

In [143]:
A*B

array([[2, 0],
       [0, 4]])

In [144]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [145]:
np.dot(A,B)

array([[5, 4],
       [3, 4]])

In [146]:
A += 3
A

array([[4, 4],
       [3, 4]])

In [147]:
A *= 3
A

array([[12, 12],
       [ 9, 12]])

In [148]:
A.sum(), A.min(), A.max()

(45, 9, 12)

In [154]:
A[0,:]

array([12, 12])

In [152]:
A[1,:]

array([ 9, 12])

In [155]:
A[:,0]

array([12,  9])

In [156]:
a = np.arange(24).reshape(2,12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [157]:
np.hsplit(a,3)

[array([[ 0,  1,  2,  3],
        [12, 13, 14, 15]]), array([[ 4,  5,  6,  7],
        [16, 17, 18, 19]]), array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [158]:
A.transpose()

array([[12,  9],
       [12, 12]])

In [159]:
np.transpose(A)

array([[12,  9],
       [12, 12]])

In [171]:
a = np.arange(1000)
a

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [172]:
import time

inicio = time.time()
np.sum(a)
fim = time.time()
print(fim - inicio)

0.0001304149627685547


In [173]:
import time

inicio = time.time()
result = 0
for elem in a:
    result += elem
fim = time.time()
print(fim - inicio)

0.00037741661071777344
